### PR TITLE
Add debug documentation #39

### LINKED ISSUE #39: Document debugging
As a developer,
I want documentation to guide me debugging the front-end and back-end
So I can use the debugger to find problems

### PR DESCRIPTION
**Pull request by cskeogh**
Add documentation on debugging. Includes setup for Visual Studio Code, if developers are using another IDE the documentation shows what is possible. There may be some slight differences depending on what platform you are running. Closes #39

### CODE REVIEW

**Review by JoshuaBuditama — COMMENTED** [review]
the README.md file in the back-end folder only contains the number "1" for the sequence number.
Is this how it's supposed to be?
There does not seem to be any problem when I read it through GitHub though.

**Comment by cskeogh** [comment]
> the README.md file in the back-end folder only contains the number "1" for the sequence number.
> Is this how it's supposed to be?
> There does not seem to be any problem when I read it through GitHub though.

Yes if looking at the raw markdown. If you install a markdown previewer, you can see the rendered output. Visual Studio Code has a markdown previewer built in (right-click on the editor Tab and select Open Preview or Ctrl+Shift+V)

**Comment by JoshuaBuditama** [comment]
Ah gotcha, no worries then.
Ready to be merged.

**Review by JoshuaBuditama — APPROVED** [review]
Ah gotcha, no worries then.
Ready to be merged.

**Pull request merged**
