### PR TITLE
Issues/1 app skeleton

### PR DESCRIPTION
**Pull request by JakeBrown**
This should close issue #1.

### CODE REVIEW

**Comment by cskeogh** [comment]
Nice work. Is it possible to use TypeScript?
Did you use create-react-app? If yes, perhaps use '--template typescript' as per https://create-react-app.dev/docs/adding-typescript/

**Comment by JakeBrown** [comment]
@cskeogh yep I used CRA. Haven't added typescript yet, I left it fairly unopinionated with regards to that. Looks like it can be added fairly easily. Just a couple of questions and I'd be happy to make the changes:

1. Do we want to use TS and JS or a mix of both?
2. Do we want to use TS for the server too?

One concern which may or may not be valid is that most React learning resources are going to be in JS. Do you think it would be an additional burden on those trying to learn JSX and React for the first time, or not a big deal? 

I'm not fussed because I'm familiar with React and I've been wanting to learn TS anyway. 

---
To add TypeScript to a Create React App project, first install it:
```
npm install --save typescript @types/node @types/react @types/react-dom @types/jest
```
Next, rename any file to be a TypeScript file (e.g. src/index.js to src/index.tsx) and restart your development server!

**Review by JoshuaBuditama — APPROVED** [review]

**Comment by JoshuaBuditama** [comment]
@cskeogh @JakeBrown 
With the TS/JS issue, I think it would be good to stick with TS for now since I recall @cskeogh mentioned that he is quite experienced in using TS, which means that we will have at least 1 person that knows what's going on.

I don't think anyone else in the group will object against this since we have brought up this issue in the previous meetings and everyone seemed to agree.

**Review by JoshuaBuditama — APPROVED** [review]

**Comment by cskeogh** [comment]
I think use TypeScript everywhere. I think TypeScript is easier than JavaScript, helps prevent errors and code completion/IntelliSense works well with TypeScript

**Comment by JakeBrown** [comment]
OK, probably best to just reject this PR and start from scratch with TS. I had a go at converting my existing code but I'm running into compilation errors with the default `tsconfig.json`. 

I'll go away and learn TS - the official React documentation is all JS unless I'm missing something. 

Over to you @cskeogh. `npx create-react-app my-app --template typescript` should do the trick. See if you can implement the useState/useContext functionality I did here, but in TS.

**Pull request closed without merging**
