### PR TITLE
Added UI device mock and additional dependency of styled-component, resolves issue #45

### PR DESCRIPTION
**Pull request by JakeBrown**
I have used this as a guide:
https://www.w3schools.com/howto/tryit.asp?filename=tryhow_css_device_smartphone

Screenshot of implementation is attached:
Screen Shot 2020-10-09 at 10 34 09 am

I have chosen to include the library styled-components which is a widely used library for including CSS in JS. 
It supports CSS `:before` and `:after` selectors which are not supported by the style prop in React.

### CODE REVIEW

**Comment by JakeBrown** [comment]
Completes issue #45

**Review by cskeogh — CHANGES_REQUESTED** [review]
When this gets merged to master, master will look like below. Can you either fix, or raise a separate issue (type: bug) to cover this.

bug02

**Comment by JakeBrown** [comment]
@cskeogh I've pushed a potential fix. One of several options, this solution sets the content panel to a fixed size and adds auto-hiding scroll bars when there is overflow. 

It will still require some changes to the Notification Page, but at least it is a more gradual/graceful failure. It's probably a good thing as it highlights there being too much content for a mobile screen. 

Screen Shot 2020-10-10 at 8 44 06 am

If you accept this fix I will create an issue to update the Notification page.

**Comment by JakeBrown** [comment]
Demo showing interaction

demo 2

**Review by cskeogh — DISMISSED** [review]
Looks good. Good to merge. Noting the slight merge conflict with master.

**Comment by JakeBrown** [comment]
@cskeogh merge conflict resolved. Looks like I need your review approval before I can merge.

**Review by cskeogh — APPROVED** [review]
Looks good to merge.

**Pull request merged**
