### PR TITLE
Issues/50/automated testing

### PR DESCRIPTION
**Pull request by JakeBrown**
- Front-end: Added a demo test to demonstrate how to write simple tests
- Front-end: Configured Github Actions to automatically run tests
- Back-end: Installed and configured Jest to work with TS
- Back-end: Added a demo test to demonstrate how to write simple tests
- Back-end: Configured Github Actions to automatically run tests

Closes issue #50

### CODE REVIEW

**Review by JoshuaBuditama — DISMISSED** [review]

**Review by cskeogh — CHANGES_REQUESTED** [review]
Back-end doesn't work with Typescript.

2 changes are required to work with Typescript (as per [docs](https://jestjs.io/docs/en/getting-started#using-typescript))

`npm install @babel/preset-typescript`

and:
``` js
// babel.config.js
module.exports = {
  presets: [
    "@babel/preset-flow",
    [
      "@babel/preset-env",
      {
        targets: {
          node: "current",
        },
      },
    ],
    '@babel/preset-typescript',
  ],
};
```

**Comment by JakeBrown** [comment]
@cskeogh the back-end tests are passing in CI... What do you mean by "doesn't work"?


 Screen Shot 2020-10-12 at 1 19 15 pm

**Comment by JakeBrown** [comment]
@cskeogh I've added the recommended babel config in commit 4431f, thought curiously it doesn't change the testing output locally or in CI.

**Review by cskeogh — APPROVED** [review]
> @cskeogh I've added the recommended babel config in commit 4431f, thought curiously it doesn't change the testing output locally or in CI.

Adding Typescript support shouldn't change the output. Thank you for making the changes. Looks good to merge.

**Pull request merged**
